#!/usr/bin/env bash
# Generate cursor/rules/hikizan.mdc from templates/ (single source): routing
# conventions (templates/CLAUDE.md) + the standard-tier opt-out preamble
# (templates/standard-preamble.md), as an always-apply Cursor rule. This is how
# the standard-tier opt-out reaches Cursor (CC uses session-context.sh; Codex
# uses its SessionStart hook; Cursor uses this always-apply rule).
#   bash scripts/gen-cursor-rule.sh           # write
#   bash scripts/gen-cursor-rule.sh --check    # fail if regen would change it
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/cursor/rules/hikizan.mdc"
gen() {
  printf '%s\n' '---'
  printf '%s\n' 'description: hikizan routing conventions and the standard-tier opt-out preamble (floors are enforced by the beforeShellExecution hook)'
  printf '%s\n' 'alwaysApply: true'
  printf '%s\n' '---'
  printf '%s\n' '<!-- generated by scripts/gen-cursor-rule.sh from templates/CLAUDE.md + templates/standard-preamble.md — do not edit by hand -->'
  printf '\n'
  cat "$ROOT/templates/CLAUDE.md"
  printf '\n'
  cat "$ROOT/templates/standard-preamble.md"
}
if [ "${1:-}" = "--check" ]; then
  if diff -q "$OUT" <(gen) >/dev/null 2>&1; then
    echo "✔ cursor/rules/hikizan.mdc up to date"
  else
    echo "✘ cursor/rules/hikizan.mdc is stale — run: bash scripts/gen-cursor-rule.sh" >&2
    exit 1
  fi
else
  mkdir -p "$ROOT/cursor/rules"
  gen > "$OUT"
  echo "✔ wrote cursor/rules/hikizan.mdc"
fi
